davidgiven/cowgol

tinycowc/Makefile
tinycowc/README.md
tinycowc/arch8080.c
tinycowc/archagc.c
tinycowc/cowgol.agc
tinycowc/globals.h
tinycowc/lexer.l
tinycowc/lunarlander.cow
tinycowc/main.c
tinycowc/mkninja.sh
tinycowc/parser.y

Merge the AGC and 8080 versions of tinycowc together.

---

examples/argv.cow
mkninja.sh
rt/cpm/argv.coh
rt/thumb2-linux/argv.coh
rt/thumb2-linux/cowgol.s
scripts/mkmidcodesh.lua
src/arch8080.ng
src/parser.y

...plus all the machinery to make it work.

Add an argv library

---

.github/workflows/ccpp.yml
examples/empty.cow
mkninja.sh
rt/80386-linux/cowgol.coh
rt/80386-linux/cowgol.s
src/arch80386.ng
src/arch8080.ng
src/codegen.c
src/globals.h
tools/newgen/globals.h
tools/newgen/lexer.l
tools/newgen/main.c
tools/newgen/parser.y

This will generate native Linux 386 binaries.

Add i386 support

---

mkninja.sh
rt/80386-linux/cowgol.coh
rt/80386-linux/file.coh
rt/cpm/cowgol.coh
rt/cpm/file.coh
rt/thumb2-linux/cowgol.coh
rt/thumb2-linux/file.coh
src/arch80386.ng
src/archthumb2.ng
src/codegen.c
src/codegen.h
src/globals.h
src/midcodes.tab
src/parser.y
tools/newgen/globals.h
tools/newgen/main.c

This reworks newgen so that most of the codegen logic is in a big table --- massive code size improvements (except on x64 where pointers are 8 bytes). Plus make the file library work on 80386 and thumb2, and also some table fixes.

More fixes.

---

.github/workflows/ccpp.yml
mkninja.sh
src/arch80386.ng
src/arch8080.ng
src/archcgen.ng
src/archthumb2.ng
src/compiler.c
src/compiler.h
src/globals.h
src/parser.y
tests/structinitialisers.good
tests/structinitialisers.test.cow
tools/newgen/main.c

You can now define complex static initialisers which will turn into binary inclusions in the output file.

Make array and record initialisers work

---

mkninja.sh
scripts/libcowgol.lua
scripts/mkmidcodescoh.lua
src/arch80386.ng
src/arch8080.ng
src/archcgen.ng
src/archthumb2.ng
src/compiler.c
src/compiler.h
src/cowcom/main.cow
src/cowcom/types.coh
src/globals.h
src/midcodes.coh.tab
src/parser.y
tests/records.good
tests/records.test.cow

Inherited records, a fix for a nasty bug which happened if you used a new partial type in a subroutine parameter list, and the midcodes library now builds.

Several more bugfixes and some native compiler work

---

mkninja.sh
rt/cgen/cowgol-cgen.h
rt/cpm/cowgol.asm
scripts/mkmidcodescoh.lua
src/arch80386.ng
src/arch8080.ng
src/archcgen.ng
src/archthumb2.ng
src/codegen.c
src/cowcom/lexer.coh
src/cowcom/main.cow
src/cowcom/midcodes.coh
src/globals.h
src/lexer.l
src/midcodes.tab
src/parser.y
tests/case.good
tests/case.test.cow
tools/newgen/main.c

I'm going to need a proper case statement, to substitute for function pointers. This implements it. Currently it uses chained comparisons, but it should be easy to extend to use true jump tables at some point.

Implement case

---

src/arch80386.ng
src/arch8080.cow.ng
src/arch8080.ng
src/archc.pat
src/archcgen.ng
src/archthumb2.ng
src/codegen.c
src/compiler.c
src/compiler.h
src/cowcom/ast.coh
src/cowcom/codegen.coh
src/cowcom/emitter.coh
src/cowcom/expressions.coh
src/cowcom/lempar.coh
src/cowcom/lexer.coh
src/cowcom/main.cow
src/cowcom/midcodes.coh
src/cowcom/parser.y
src/cowcom/symbols.coh
src/cowcom/types.coh
src/midcodes.coh.tab
src/midcodes.tab
src/parser.y
tests/conditionals.good
tests/conditionals.test.cow
third_party/lemon/lemon-cowgol.c
tools/newgen/main.c

I finally worked out how to do fallthrough conditionals --- it requires walking the AST a couple of times, which is bad. But this knocked a full 3% of the binary size.
Plus, lots of work on the native compiler. It's looking a bit big TBH. I'm wondering whether it will fit.

More incremental work, including much more optimised conditionals

---

mkninja.sh
rt/cpm/cowgol.asm
rt/cpm/cowgol.coh
src/arch8080.cow.ng
src/arch8080.ng
src/codegen.c
src/cowcom/emitter.coh
src/cowcom/expressions.coh
src/cowcom/lempar.coh
src/cowcom/lexer.coh
src/cowcom/main.cow
src/cowcom/parser.y
src/cowcom/symbols.coh
src/cowcom/types.coh
src/midcodes.coh.tab
third_party/lemon/lemon-cowgol.c
third_party/zmac/zmac.y
tools/newgen/main.c

Most of it is working now! Plus some hosted compiler fixes and code size improvements.

Lots more native compiler work.

---

rt/80386-linux/cowgol.inc
rt/malloc.coh
rt/thumb2-linux/cowgol.coh
rt/thumb2-linux/cowgol.inc
src/cowcom/lempar.coh
src/cowcom/lexer.coh
src/cowlink/cooread.coh
src/oldcom/arch80386.ng
src/oldcom/archthumb2.ng
tests/conditionals.good
tests/conditionals.test.cow
tools/newgen/main.c

Fix some codegen bugs so that cowcom now works when compiled with olx386 and olxthumb2.

Fix olx386 and olxthumb2.

---

src/cowcom/arch80386.cow.ng

Apply a minor fix which makes the compiled compiler actually work now.

---

bootstrap/cowcom.cgen.bootstrap.c
bootstrap/cowlink.cgen.bootstrap.c

Update the bootstrap compilers.

---

README.md
dist/bbct/build.lua
src/cowfe/lexer.coh

Final bugfixes for the BBC Micro demo and documentation

---

README.md
src/cowasm/archpdp11.cow
src/cowbe/archpdp11.cow.ng
src/cowlink/archv7unix.coh

This adds bseg, cseg and dseg support to the assembler, apparently working, and fixes a bunch of things so that, hopefully, the compiler runs on the PDP11.

More PDP11 fixes

---

README.md

Document the thumb2 backend, as it now seems to be working.

---

dist/msdos/demo.bat
rt/msdos/argv.coh
rt/msdos/cowgol.coh
src/cowlink/archmsdos.coh

...which got broken by the EXE change.

Fix DOS command line and file access

---

src/cowasm/arch6303.cow
src/cowasm/archpdp11.cow
src/cowasm/archtlcs90.cow
src/cowasm/build.lua
src/cowasm/cowasm.coh
src/cowdis/archtlcs90.cow

This adds the assembler written during the video.

Add the new TLCS90 assembler.

---

README.md

Document the Atari ST port.

---

README.md
dist/ataritos/build.lua
examples/filetester.cow
mkninja.lua
rt/ataritos/argv.coh
rt/ataritos/cowgol.coh
rt/ataritos/file.coh
toolchains.lua
tools/ataritosemu/gemdos.c
tools/ataritosemu/sim.c
tools/ataritosemu/sim.h

File access now works; the compiler now runs on an emulated Atari ST.

Fix the Atari ST syscall library.

---

src/cowasm/archpdp11.cow

not sure how to fix the @(R) case, tbh

cowasm: fix SOB insn on pdp11

---

rt/unixv7/cowgol.coh
rt/unixv7/file.coh
src/cowasm/archpdp11.cow
src/cowasm/cowasm.coh

cowasm can now assemble itself under apout.

pdp11: handle out of memory condition in cowasm and fix unixv7 runtime.

---

rt/bk10dx/argv.coh
rt/bk10dx/build.py
rt/bk10dx/cowgol.coh
rt/bk10dx/cowgol.cos
rt/bk10dx/crtany.coh
rt/bk10dx/file.coh
src/cowlink/archbk10dx.coh
src/cowlink/build.py
src/toolchains.py

DX-DOS itself is experimental (only one beta release in 1995), but has a rather simple API, a command line interpreter and uses FAT filesystem.

Add experimental runtime for DX-DOS on Electronika BK home computers.
