mkninja.sh
rt/80386-linux/cowgol.coh
rt/80386-linux/cowgol.s
rt/80386-linux/file.coh
rt/common.coh
rt/cpm/cowgol.asm
rt/cpm/cowgol.coh
rt/cpm/file.coh
rt/malloc.coh
rt/thumb2-linux/cowgol.coh
rt/thumb2-linux/cowgol.s
rt/thumb2-linux/file.coh
scripts/uncoo.lua
src/arch80386.ng
src/arch8080.ng
src/archthumb2.ng
src/codegen.c
src/compiler.c
src/compiler.h
src/cowlink/cooread.coh
src/cowlink/graph.coh
src/cowlink/main.cow
src/emitter.c
src/emitter.h
src/globals.h
src/main.c
src/parser.y
tests/shifts-16bit.test.cow
tests/shifts-32bit.good
tests/shifts-32bit.test.cow

Switch the compiler output format to coofiles, plus all the machiner; cowlink now works well enough to load and walk the call graph from a coofile. Lots of knock-on changes and fixes including partial type support (needed for recursive types).

Incremental work towards working coofiles

---

mkninja.lua
rt/cpm/build.lua
rt/cpm/cowgol.cos
src/build.lua
src/cowwrap/reader.coh

It should now actually work, with cross-references and everything (although the output coofiles could use optimisation). Port the CP/M standard library into cos format.

More cowwrap work.

---

src/cowcom/arch8080.cow.ng
src/cowcom/build.lua
src/cowcom/codegen.coh
src/cowcom/emitter.coh
src/cowcom/main.cow
src/cowcom/regcache.coh
src/oldcom/arch80386.ng
src/oldcom/compiler.c
src/oldcom/parser.y
tools/newgen/globals.h
tools/newgen/lexer.l
tools/newgen/main.c
tools/newgen/parser.y

This adds a really simplistic register cache mechanism to avoid reloading values if they're already available in a register. It works, but not as well as I hoped: after adding the cache the binary size is actually bigger, at 51185 bytes (up from 50927 bytes).

Implement the register cache

---

mkninja.lua
rt/cpm/cowgol.cos
rt/cpmz/argv.coh
rt/cpmz/build.lua
rt/cpmz/cowgol.coh
rt/cpmz/cowgol.cos
rt/cpmz/file.coh
src/build.lua
src/cowcom/arch8080.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/build.lua
src/cowcom/codegen.coh
src/cowcom/emitter.coh
src/cowcom/regcache.coh
toolchains.lua
tools/cpmemu/emulator.c
tools/newgen/globals.h
tools/newgen/lexer.l
tools/newgen/main.c
tools/newgen/parser.y

This adds a working Z80 backend, complete with index register support; although lack of aliasing analysis makes it less useful than you might think because every time you write through ix or iy you need to discard all values in case they've changed. Also, the register allocator is rather reluctant to use them for some reason.
The code size is pretty bad --- very slightly smaller than the 8080. This appears mostly to be the fault of 32-bit arithmetic, which uses the shadow registers on the Z80 but was done through helper routines on the 8080. So the 8080 can add two numbers on the stack in three bytes for the call to the helper, but the Z80 takes four. Routines that use 32-bit maths typically have every other instruction being exx.

Add a Z80 backend

---

src/cowcom/arch8080.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/expressions.coh
src/cowcom/lempar.coh
src/cowcom/midcodec.coh
src/cowcom/parser.y
tools/newgen/main.c

Continue picking away at the 8080 and Z80 backends. This actually knocks quite a lot off the compiler size while also improving the code quality. The Z80 self compiler is down from 57179 to 54938 bytes, and the 8080 self compiler 51442 to 49629 bytes. Still too big, still better.

Even more optimisations.

---

src/cowcom/arch8080.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/regcache.coh
tools/newgen/globals.h
tools/newgen/main.c
tools/newgen/parser.y

Previously it didn't, and was hardwired to uint32. This actually allows it to be configurable for better register cache code.

Fix the machine word stuff to actually work

---

Makefile
mkninja.lua
rt/cgen/build.lua
rt/cgen/cowgol.h
src/build.lua
src/cowcom/arch8080.cow.ng
src/cowcom/archcgen.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/build.lua
src/cowcom/emitter.coh
src/cowcom/main.cow
src/cowcom/namespace.coh
src/cowcom/parser.y
src/cowcom/symbols.coh
src/cowlink/arch8080.coh
src/cowlink/archcgen.coh
src/cowlink/build.lua
src/cowlink/graph.coh
src/cowlink/main.cow
src/midcodes.coh.tab
toolchains.lua

This adds a ncgen target for cowcom, which is the last big step before bootstrapping and removal of oldcom completely. (Or at least it will be once ncgen compiles cowcom correctly, rather than just passing the tests.)

Add a cowcom ncgen target

---

src/cowcom/codegen.coh
tools/newgen/main.c

The consumable registers and template byte tables in the codegen rules contained a lot of zero bytes. We can omit these from the code by being cleverer about how we encode the tables. For the 8080, this saves 1073 bytes; for the Z80, which has more complex rules, this saves a very satisfactory 2689 bytes, making the Z80 self compiler now 52512 bytes, which is slowly approaching adequate.

Compress the rules tables

---

Makefile
include/coodecls.coh
rt/cgen/argv.coh
rt/cgen/cowgol.h
rt/common.coh
scripts/mkmidcodescoh.lua
src/cowcom/arch8080.cow.ng
src/cowcom/archcgen.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/build.lua
src/cowcom/codegen.coh
src/cowcom/parser.y
src/cowlink/asmwrite.coh
src/cowlink/graph.coh
src/midcodes.coh.tab
tests/conditionals.good
tests/conditionals.test.cow
tests/inputparams.good
tests/inputparams.test.cow
toolchains.lua

Turns out there was a fundamental design issue in cowcom in the way arguments were passed which was causing bad code when subroutines were embedded inside conditionals or complex expressions. This resolves this. We now have a nncgen toolchain which uses the compiler produced by ncgen, which works absolutely fine; the cpm and cpmz targets use nncgen.

ncgen can now build a working compiler

---

src/cowcom/arch6502.cow.ng
src/cowcom/types.coh
tests/addsub-16bit.good
tests/addsub-16bit.test.cow
tools/newgen/main.c

After deciding that I couldn't optimise it any more, I optimised it some more. cowlink.bbct has gone from 9155 to 8779 bytes, and cowcom.8080.bbct has gone from 57843 to 56960. Sadly the 6502 compilers are still way too big to run on an actual 6502.

Lots of 6502 backend optimisations

---

rt/bbct/cowgol.cos
rt/bbct/file.coh
src/cowcom/arch6502.cow.ng
src/cowcom/arch8080.cow.ng
src/cowcom/archz80.cow.ng
src/cowcom/emitter.coh
src/cowcom/lexer.coh
src/cowcom/parser.y
src/cowcom/regcache.coh
src/cowlink/archbbct.coh
src/cowlink/emitter.coh
tests/addsub-32bit.good
tests/addsub-32bit.test.cow
tests/case.good
tests/case.test.cow

I went through the 6502 backend and cleaned up a lot --- there was a lot of stray code which served no purpose. The 65c02 compiler, compiled with the 8080 compiler, went from 58828 bytes to 58639 bytes. I also found some places where I could actually improve the 6502 generated code: cowcom.cgen, compiled for the 6502, went from 52451 bytes to 52361 bytes.
...and _then_ I realised I can make my aliasing problems go away by modifying the language to forbid it --- the only time it's a problem is when taking the address of a simple variable, as that's the only time it's a problem. (Taking the address of a record isn't a problem as it cannot change, and values of members are never cached.) Turns out there's only two places in the code base which do this, one of which is some evil in the bbct …

More minor byte shaving and optimisations

---

rt/bbct/cowgol.cos
src/cowcom/arch6502.cow.ng
src/cowcom/arch8080.cow.ng
src/cowcom/archz80.cow.ng
third_party/zmac/build.lua

Turns out I completely forgot some easy wins! cowcom-8080.bbct goes from 57165 to 56588 bytes, which is a drop of about 1%, which is really nice. cowlink-bbct goes down from 8784 to 8647 bytes.
The extra rules caused cowcom-65c02.ncpmz to go over the limit and it stopped compiling, but I figured out how to enable automatic relative jumps, which I wanted anyway. That knocked a kilobyte off the compiler size. cowcom-65c02.ncpmz has gone from 60236 to 60062 bytes.

Add some more optimisations

---

build/yacc.lua

Hello.
Berkeley Yacc does not have a --defines= flag. So we should specify bison.
This lets cowgol build and run on systems where yacc isn't bison; for example, OpenBSD (where cowgol has been tested and working).
Thanks!

The --defines= flag is a GNU-ism, so we need to specify bison -y.

---

src/cowbe/arch6303.cow.ng
src/cowbe/arch6502.cow.ng
src/cowbe/arch6502i.cow.ng
src/cowbe/arch80386.cow.ng
src/cowbe/arch8080.cow.ng
src/cowbe/archbasic.cow.ng
src/cowbe/archcgen.cow.ng
src/cowbe/archpdp11.cow.ng
src/cowbe/archthumb2.ng
src/cowbe/archz80.cow.ng
src/cowfe/namespace.coh
src/cowfe/parser.y
src/midcodes.coh.tab

This replaces LOADx and STOREx with DEREFx and STOREx. STOREx takes a DEREFx as the second parameter, so:
STORE2(r1, r2) # [r2] := r1
becomes
STORE2(r1, DEREF2(r2)) # [r2] := r1
(A bare DEREFx not inside a STOREx does a load.)
This allows (much) smaller rule tables for addressing-mode-heavy platforms like the x86 and 6809, as the same rule can generate an lvalue for use by either loads or stores.

Rework how loads and stores work to be more addressing-mode friendly

---

rt/cpm/cowgol.coh

This allows us to write interactive Cowgol programs.
Works with cpmemu.
I have an RPN calculator that demonstrates this works: https://github.com/ibara/cowgol-utilities/blob/main/rpn.cow
I can run it as `cpmemu rpn.com` and it does the right thing.
(Ignore the spaghetti code of the calculator itself.)
Only have get_char() code for 8080 CP/M at the moment, though I plan to implement at least Z80 CP/M and Unix soon.
And obviously I'm OK with a name change. I just chose get_char() because of the analogous print_char().

Implement single-character get_char() for 8080 CP/M.

---

rt/cpmz/cowgol.coh

Straight translation from 8080 to Z80 mnemonics.
Works with cpmemu.

Implement get_char() for Z80 CP/M.

---

rt/cgen/cowgol.coh

Cgen get_char. Unsurprisingly uses getchar() from libc.
Works on my OpenBSD machine.

Implement Cgen get_char().

---

src/cowbe/arch6303.cow.ng
src/cowbe/arch6502.cow.ng
src/cowbe/arch80386.cow.ng
src/cowbe/arch8080.cow.ng
src/cowbe/arch8086.cow.ng
src/cowbe/archpdp11.cow.ng
src/cowbe/archthumb2.cow.ng
src/cowbe/codegen.coh
tools/newgen/main.c

This makes dealing with them much easier. In the rule files, you can now say 'uses all' to corrupt all registers, and still have normal inputs and outputs.

Instructions now track used registers seperately from inputs and outputs

---

include/coodecls.coh
src/cowbe/arch68000.cow.ng
src/cowlink/archataritos.coh
src/cowlink/streams.coh

Unlike the other platforms, this uses a single global pointer to ws; this is simpler than having a per-subroutine one, as well as making subroutine prologue and epilogues less complex. It takes the size of cowfe for the 68000 down from 107046 bytes to 97275 bytes, which is respectable. Also applies some other minor optimisations.

Use a6-offsetting rather than absolute addresses for accessing the workspace.

---

doc/language.md

When I copy-pasted this piece of code for testing, it tripped on the missing braces. Uh, and on the missing import that I forgot to add in this PR.

Doc fix: no sub without () allowed

---

src/cowbe/arch8080.cow.ng
src/cowbe/archpdp11.cow.ng

SUB1 typo is hidden by SUB->ADD transform in midcodec.h
DEREF thing looks like a bug in rule matcher?

8080, pdp11: typo fixes
